## Package import

In [2]:
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests

## Test for Single Mean

In [3]:
# Import: Rossmann Store Sales Data 

sales_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Rossmann_Store_Sales/Rossmann_Store_Sales.zip", compression="zip")
print(sales_data.shape)
print(sales_data.info())
sales_data.sample(5)

C:\Users\HP\AppData\Local\Temp\ipykernel_10308\2653865927.py:3: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  sales_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Rossmann_Store_Sales/Rossmann_Store_Sales.zip", compression="zip")

(1017209, 18)
<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  str
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  str
 10  Assortment                 1017209 non-null  str
 11  CompetitionDistance        1017209 non-null  int64
 12  CompetitionOpenSinceMonth  1017209 non-null  int64
 13  CompetitionOpenSinceYear   1017209 non-null  int64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            1017209 non-null  int64
 16  Promo2SinceYear            1017209 non-null  int64
 17  PromoInterval              1017209 non-null  str
dtypes: int64(13), object(1), str(4)
memory usage: 139.7+ MB
None

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
859214,335,3,22-05-2013,12016,2673,1,0,0,0,b,a,90,0,0,1,31,2013,"Jan,Apr,Jul,Oct"
481230,336,6,26-04-2014,10836,1694,1,0,0,0,a,a,190,7,2014,0,0,0,0
912260,976,5,05-04-2013,6282,694,1,0,0,1,a,a,4180,0,0,0,0,0,0
646407,493,5,29-11-2013,7942,823,1,0,0,0,d,c,1150,0,0,1,14,2011,"Jan,Apr,Jul,Oct"
28997,8,7,05-07-2015,0,0,0,0,0,0,a,a,7520,10,2014,0,0,0,0

In [11]:
# Testing the Null Hypothesis: Average number of customers = 700

sales_sample=sales_data.sample(n=100,random_state=55)   # n = 100 means Sample size = 100

ztest, pval = stests.ztest(sales_sample["Customers"], x2=None, value=700)   # returns a tuple having ztest and p- value
print(ztest)
print("P-Value", float(pval))

if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")
    
# Null Hypothersis will be accepted for avg no. of customers = 650

-2.6063279223993843
P-Value 0.009151879639808083
reject null hypothesis

In [13]:
# Testing the Null Hypothesis: Average sales = 5600

sales_sample=sales_data.sample(n=100,random_state=55)

ztest ,pval = stests.ztest(sales_sample["Sales"], x2=None, value=5600)
print(ztest)
print("P-Value", float(pval))

if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

0.03487735992339417
P-Value 0.9721775337914002
accept null hypothesis

## Test for Two Means

In [15]:
sales_sample=sales_data.sample(n=100,random_state=55)

# ztest(sample1, sample2) performs a two-sample Z-test and check : Is the mean sales of Promo = 1 significantly different from Promo = 0?
# H₀ (Null hypothesis): Mean(Sales | Promo=0) = Mean(Sales | Promo=1)
# H₁ (Alternative hypothesis): Mean(Sales | Promo=0) ≠ Mean(Sales | Promo=1)
ztest ,pval = stests.ztest(sales_sample["Sales"][sales_sample["Promo"]==0], 
                            sales_sample["Sales"][sales_sample["Promo"]==1])
print(ztest)
print("P-Value", float(pval))

if pval<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

-5.124020966949121
P-Value 2.9908770229173153e-07
reject null hypothesis

## Testing Multiple Means
Using **F-tests** : which is used to compare mean across 3 or more groups

In [34]:
sales_sample=sales_data.sample(n=300,random_state=55)

# to check whether average sales differ across different store types
# Null hypothesis (H₀): All store types have the same mean sales
# Alternative hypothesis (H₁): At least one store type has a different mean

F, p = stats.f_oneway(sales_sample["Sales"][sales_sample["StoreType"]=="c"],
                        sales_sample["Sales"][sales_sample["StoreType"]=="b"],
                        sales_sample["Sales"][sales_sample["StoreType"]=="d"] 
                    )
print(F)  # Small F → group means are similar
print("p-value for significance is: ", p)

if p<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

0.9508412401160866
p-value for significance is:  0.3890072124516406
accept null hypothesis

In [35]:
# Null hypothesis (H₀): Average number of customers is the same on all selected days
# Alternative hypothesis (H₁): At least one day has a different average number of customers
F, p = stats.f_oneway(sales_sample["Customers"][sales_sample["DayOfWeek"]==2],
                        sales_sample["Customers"][sales_sample["DayOfWeek"]==3],
                        sales_sample["Customers"][sales_sample["DayOfWeek"]==4])

print(F)
print("p-value for significance is: ", p)

if p<0.05:
    print("reject null hypothesis")
else:
    print("accept null hypothesis")

3.132527284377572
p-value for significance is:  0.0467466384988462
reject null hypothesis

## Chi-Square Test of Independence

In [36]:
bank_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/python_5days/master/Day3_Files/Datasets/bank-full.csv",sep=';')
print(bank_data.shape)
bank_data.info()

(45211, 17)
<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 5.9 MB

In [44]:
bank_data.sample(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
13191,56,retired,married,secondary,no,307,no,yes,cellular,8,jul,175,1,-1,0,unknown,no
31305,43,technician,married,secondary,no,1358,no,no,cellular,10,mar,159,3,-1,0,unknown,yes
2205,29,admin.,single,secondary,no,382,yes,no,unknown,12,may,460,1,-1,0,unknown,no
28778,46,blue-collar,single,secondary,no,332,no,no,cellular,30,jan,11,4,-1,0,unknown,no
15297,52,technician,divorced,tertiary,no,0,no,no,cellular,18,jul,454,1,-1,0,unknown,no
36820,48,blue-collar,single,secondary,no,574,no,no,cellular,12,may,328,2,-1,0,unknown,no
6987,52,blue-collar,married,primary,no,-211,yes,yes,unknown,28,may,153,2,-1,0,unknown,no
38344,35,admin.,single,tertiary,no,1374,yes,no,cellular,15,may,319,1,-1,0,unknown,no
38526,56,retired,divorced,tertiary,no,-458,yes,no,cellular,15,may,406,4,296,3,failure,no
12332,36,blue-collar,married,secondary,no,2103,no,yes,unknown,26,jun,71,1,-1,0,unknown,no

In [43]:
categorical_cols=[col for col in bank_data.columns if bank_data[col].dtypes in ["str"]]
print(categorical_cols)

['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

In [ ]:
bank_data_sample=bank_data.sample(300)
import scipy.stats as stats

# checking whether each categorical column matter for predicting the target variable y
# H₀ (Null hypothesis): The categorical feature and target y are independent
# H₁ (Alternative hypothesis): The feature and y are dependent (related) -> feature can be dropped
for col in categorical_cols:
    crosstab =pd.crosstab(bank_data_sample[col], bank_data_sample['y'])
    print(crosstab)
    
    Chi=stats.chi2_contingency(crosstab)   # This returns 4 values: (chi2_stat, p_value, dof, expected_freq)
    p=Chi[1]   # getting p_value
    print("p-value for significance is: ",p )
    if p<0.05:
        print("reject null hypothesis")
    else:
        print("accept null hypothesis")
    print("============================\n")

y              no  yes
job
admin.         25    5
blue-collar    60    7
entrepreneur    8    1
housemaid       6    1
management     53    9
retired         8    2
self-employed   6    1
services       35    4
student         3    2
technician     43    7
unemployed     10    1
unknown         2    1
p-value for significance is:  0.889151588205179
accept null hypothesis
============================

y          no  yes
marital
divorced   30    5
married   162   25
single     67   11
p-value for significance is:  0.9811924857532067
accept null hypothesis
============================

y           no  yes
education
primary     40    6
secondary  141   19
tertiary    67   13
unknown     11    3
p-value for significance is:  0.6553604032020133
accept null hypothesis
============================

y         no  yes
default
no       250   41
yes        9    0
p-value for significance is:  0.4719712750878018
accept null hypothesis
============================

y         no  yes
housing
no       114   21
yes      145   20
p-value for significance is:  0.4885580183327445
accept null hypothesis
============================

y      no  yes
loan
no    221   35
yes    38    6
p-value for significance is:  1.0
accept null hypothesis
============================

y           no  yes
contact
cellular   154   36
telephone   17    2
unknown     88    3
p-value for significance is:  0.0015467953201451052
reject null hypothesis
============================

y      no  yes
month
apr    13    6
aug    42    6
dec     0    1
feb    15    3
jan    15    1
jul    32    5
jun    38    6
mar     2    1
may    82    6
nov    16    2
oct     2    4
sep     2    0
p-value for significance is:  0.000882216882798959
reject null hypothesis
============================

y          no  yes
poutcome
failure    23    4
other      12    2
success     5    7
unknown   219   28
p-value for significance is:  8.435921617774141e-05
reject null hypothesis
============================

y     no  yes
y
no   259    0
yes    0   41
p-value for significance is:  2.2455070488738745e-65
reject null hypothesis
============================